services:
  robzap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robzap
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - evolution-network

networks:
  evolution-network:
    external: true
