services:
  robzap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robzap
    restart: unless-stopped
    ports:
      - "8002"
    environment:
      - PYTHONUNBUFFERED=1

networks:
  evolution-network:
    external: true